// Code generated by protoc-gen-go-cloudfunction. DO NOT EDIT.

package example

import (
	"context"
	"net/http"

	"github.com/aiocean/cfutil"
)

type GetWallpaperHandlerFunc = func(context.Context, *GetWallpaperRequest) (*GetWallpaperResponse, error)

func GetWallpaperHandler(w http.ResponseWriter, r *http.Request, do GetWallpaperHandlerFunc) {
	if err := cfutil.ApplyCors(w, r); err != nil {
		cfutil.WriteError(w, r, http.StatusInternalServerError, err)
		return
	}
	if err := cfutil.ApplyContentType(w, r); err != nil {
		cfutil.WriteError(w, r, http.StatusInternalServerError, err)
		return
	}
	var request GetWallpaperRequest
	if err := cfutil.ReadRequest(r, &request); err != nil {
		cfutil.WriteError(w, r, http.StatusBadRequest, err)
		return
	}
	response, err := do(r.Context(), &request)
	if err != nil {
		cfutil.WriteError(w, r, http.StatusInternalServerError, err)
		return
	}
	if err := cfutil.WriteResponse(w, r, response); err != nil {
		cfutil.WriteError(w, r, http.StatusInternalServerError, err)
	}
}
